# Generated by Django 2.1.3 on 2018-11-06 18:45

import book.models
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100)),
                ('edition', models.IntegerField()),
                ('tags', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('NON-EDUCATIONAL', 'NON-EDUCATIONAL'), ('COMEDY', 'COMEDY'), ('FICTION', 'FICTION'), ('EDUCATIONAL', 'EDUCATIONAL'), ('DRAMA', 'DRAMA'), ('THRILLER', 'THRILLER')], max_length=50, null=True)),
                ('description', models.CharField(max_length=300)),
                ('isbn', models.CharField(default='0000', max_length=300, primary_key=True, serialize=False)),
                ('rating', book.models.IntegerRangeField(default=5)),
                ('availability', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='UsersBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending_request', book.models.IntegerRangeField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Book')),
            ],
        ),
    ]
