# Generated by Django 2.1.3 on 2018-11-06 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersbook',
            name='owner_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='users.UserProfile'),
        ),
        migrations.AddField(
            model_name='usersbook',
            name='taken_user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hasbook', to='users.UserProfile'),
        ),
    ]
