# Generated by Django 2.1.2 on 2018-10-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100)),
                ('edition', models.IntegerField()),
                ('description', models.IntegerField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='book_meta',
        ),
    ]
