# Generated by Django 2.1.3 on 2018-11-03 15:22

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20181103_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='availability',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('NON-EDUCATIONAL', 'NON-EDUCATIONAL'), ('EDUCATIONAL', 'EDUCATIONAL')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(blank=True, choices=[('NON-EDUCATIONAL', 'NON-EDUCATIONAL'), ('EDUCATIONAL', 'EDUCATIONAL')], max_length=100, null=True),
        ),
    ]
