# Generated by Django 2.1.2 on 2018-11-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20181030_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='id',
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(default='0000', max_length=300, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.DecimalField(decimal_places=0, default=5, max_digits=1),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(max_length=300),
        ),
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='book.Tags'),
        ),
    ]
