# Generated by Django 2.1.3 on 2018-11-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20181103_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='availability',
            field=models.IntegerField(default=1),
        ),
    ]
