# Generated by Django 2.1.2 on 2018-11-01 17:19

import book.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20181101_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=book.models.IntegerRangeField(),
        ),
    ]
