# Generated by Django 2.1.2 on 2018-11-03 18:21

import book.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20181103_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersbook',
            name='pending_request',
            field=book.models.IntegerRangeField(default=1),
        ),
    ]
