# Generated by Django 2.1.2 on 2018-11-01 17:54

import book.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_usersbook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersbook',
            old_name='isbn',
            new_name='book',
        ),
        migrations.AlterField(
            model_name='usersbook',
            name='quantity',
            field=book.models.IntegerRangeField(default=1),
        ),
    ]
