# Generated by Django 2.1.2 on 2018-11-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20181101_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(choices=[('ED', 'Education'), ('ND', 'Non-Education')], max_length=2),
        ),
    ]
