# Generated by Django 2.1.3 on 2018-11-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20181101_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(blank=True, choices=[('EDUCATIONAL', 'EDUCATIONAL'), ('NON-EDUCATIONAL', 'NON-EDUCATIONAL')], max_length=100, null=True),
        ),
    ]
