# Generated by Django 2.1.3 on 2018-11-03 06:14

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20181103_0554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='tags',
        ),
        migrations.AddField(
            model_name='book',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('EDUCATIONAL', 'EDUCATIONAL'), ('NON-EDUCATIONAL', 'NON-EDUCATIONAL')], max_length=50, null=True),
        ),
    ]
