# Generated by Django 2.1.3 on 2018-11-03 06:57

import book.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20181101_1919'),
        ('book', '0008_auto_20181103_0614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersbook',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='usersbook',
            name='user',
        ),
        migrations.AddField(
            model_name='usersbook',
            name='owner_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='users.UserProfile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersbook',
            name='taken_user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hasbook', to='users.UserProfile'),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=book.models.IntegerRangeField(default=5),
        ),
    ]
