# Generated by Django 2.1.2 on 2018-11-01 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_auto_20181101_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
