# Generated by Django 2.1.2 on 2018-11-03 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_auto_20181103_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(blank=True, choices=[('COMEDY', 'COMEDY'), ('FICTION', 'FICTION'), ('THRILLER', 'THRILLER'), ('DRAMA', 'DRAMA'), ('EDUCATIONAL', 'EDUCATIONAL'), ('NON-EDUCATIONAL', 'NON-EDUCATIONAL')], max_length=100, null=True),
        ),
    ]
