# Generated by Django 2.1.2 on 2018-11-03 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_auto_20181101_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersbook',
            name='quantity',
        ),
    ]
