# Generated by Django 2.1.2 on 2018-11-03 21:00

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_auto_20181103_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('FICTION', 'FICTION'), ('EDUCATIONAL', 'EDUCATIONAL'), ('COMEDY', 'COMEDY'), ('THRILLER', 'THRILLER'), ('NON-EDUCATIONAL', 'NON-EDUCATIONAL'), ('DRAMA', 'DRAMA')], max_length=50, null=True),
        ),
    ]
