# Generated by Django 2.1.3 on 2018-11-04 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20181103_1830'),
        ('book', '0014_auto_20181103_2100'),
    ]

    operations = [
    ]
